import { describe, expect, it } from "vitest";

import { runCli } from "../src/index.js";
import { renderSystemdUnit } from "../src/systemd.js";

describe("renderSystemdUnit", () => {
  it("renders a restarting service that tails the selected log", () => {
    const unit = renderSystemdUnit({
      cliPath: "/usr/local/bin/crawlytics",
      file: "/var/log/nginx/access.log",
      format: "apache",
      intervalMs: 750,
      key: "test-key",
      nodePath: "/usr/bin/node",
      url: "https://analytics.example.com"
    });

    expect(unit).toContain("# Generated by crawlytics ingest-cli.");
    expect(unit).toContain("Restart=always");
    expect(unit).toContain(
      "ExecStart=/usr/bin/node /usr/local/bin/crawlytics tail --key test-key --url https://analytics.example.com --format apache --file /var/log/nginx/access.log --interval 750"
    );
  });
});

describe("runCli systemd", () => {
  it("prints the unit to stdout", async () => {
    const stdout = createWriter();
    const stderr = createWriter();

    const exitCode = await runCli(
      [
        "systemd",
        "--key",
        "test-key",
        "--url",
        "https://analytics.example.com",
        "--format",
        "apache",
        "--file",
        "/var/log/nginx/access.log"
      ],
      {
        cliPath: "/usr/local/bin/crawlytics",
        nodePath: "/usr/bin/node",
        stderr,
        stdout
      }
    );

    expect(exitCode).toBe(0);
    expect(stderr.output).toBe("");
    expect(stdout.output).toContain("Restart=always");
    expect(stdout.output).toContain(
      "ExecStart=/usr/bin/node /usr/local/bin/crawlytics tail --key test-key --url https://analytics.example.com --format apache --file /var/log/nginx/access.log"
    );
  });
});

function createWriter(): { output: string; write(chunk: string): void } {
  return {
    output: "",
    write(chunk: string): void {
      this.output += chunk;
    }
  };
}
