import type { LogFormat } from "./types.js";

export interface RenderSystemdUnitOptions {
  cliPath: string;
  file: string;
  format: LogFormat;
  key: string;
  nodePath: string;
  url: string;
  fieldMap?: Record<string, string>;
  intervalMs?: number;
}

export function renderSystemdUnit(options: RenderSystemdUnitOptions): string {
  const execArgs = [
    options.nodePath,
    options.cliPath,
    "tail",
    "--key",
    options.key,
    "--url",
    options.url,
    "--format",
    options.format,
    "--file",
    options.file
  ];

  if (options.fieldMap !== undefined) {
    // Without it a jsonl unit starts a tailer that recognises nothing — and a
    // tailer that recognises nothing still reports "active (running)".
    execArgs.push(
      "--field-map",
      Object.entries(options.fieldMap)
        .map(([key, path]) => `${key}=${path}`)
        .join(",")
    );
  }

  if (options.intervalMs !== undefined) {
    execArgs.push("--interval", String(options.intervalMs));
  }

  return [
    "# Generated by crawlytics ingest-cli.",
    "# Review the paths and credentials before installing this unit.",
    "[Unit]",
    `Description=Crawlytics log tailer for ${options.file}`,
    "After=network-online.target",
    "Wants=network-online.target",
    "",
    "[Service]",
    "Type=simple",
    "Restart=always",
    "RestartSec=5",
    `ExecStart=${execArgs.map(quoteExecArg).join(" ")}`,
    "",
    "[Install]",
    "WantedBy=multi-user.target",
    ""
  ].join("\n");
}

function quoteExecArg(value: string): string {
  if (/^[A-Za-z0-9_./:@%+=,-]+$/u.test(value)) {
    return value;
  }

  return `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"').replaceAll("$", "\\$")}"`;
}
